export const spacing = {
    screen: 24,
    section: 32,
    headerGap: 16,
    cardGap: 16,
    cardPadding: 20,
    button: 12,
    contentGap: 12,
    fieldGap: 18,
    labelGap: 8,
    formGap: 28,
    inputHeight: 50,
    inputPadding: 16,
    buttonHeight: 48,
    buttonPadding: 20,
    linkPadding: 8,
    radius: 8,
    formMaxWidth: 520,
} as const;
